import {ROWS,COLS,CELLS,FORMAT,LATTICE,SHELLS,PRESETS,CAMERAS,address,neighbours,blankProject,validateProject,poseAt,parseCSV,recordsFromCSV,exampleRecords} from './core.js?v=0.3.9';
import {AuraView} from './renderer.js?v=0.3.9';
import {target,validateTarget,targetKey,targetLabel,remembered,remember,recordTarget,recordsAt,KIND_NAMES,stackColour,selectFacetGroup} from './spatial.js?v=0.3.9';
import {mountSpatial} from './spatial-ui.js?v=0.3.9';
import {mountWorkspace} from './workspace.js?v=0.3.9';
const $=id=>document.getElementById(id),page=document.body.dataset.page;
const KEY='aura-matrix-studio:v4:project',LEGACY_KEY='aura-matrix-studio:v3:project';let project=blankProject(),history=[],selectedId=null,shell=0,cell=null,face='O',view=null,shape='horn',time=0,playing=false,shotIndex=0,recording=null,playingLast=0,pendingCSV=null,toastTimer;
let selection=null,pickKind='facet',spatialUI=null,multipleFacets=false;
const facetCells=()=>project.facetSelections[`${shell}/${face}`]||[];
const pickedFacets=()=>selection?.kind==='facet'?(facetCells().length?facetCells():[selection.index]).map(n=>target(shell,face,'facet',n)):[];
const id=()=>crypto.randomUUID();
function notify(message){$('toast').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').textContent='',7000);}
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function saveStatus(text){if($('save-status'))$('save-status').textContent=text;}
try{const saved=localStorage.getItem(KEY)??localStorage.getItem(LEGACY_KEY)??localStorage.getItem('aura-matrix-studio:v2:project')??localStorage.getItem('aura-matrix-studio:v1:project');if(saved)project=validateProject(JSON.parse(saved));saveStatus('Saved on this browser');}catch(e){saveStatus('Stored project could not be read. A blank session is open.');notify('The stored copy was left untouched. Import a backup to recover it.');}
function commit(next){spatialUI?.stop();next=validateProject(next);history.push(project);project=next;try{localStorage.setItem(KEY,JSON.stringify(project));saveStatus('Saved on this browser');}catch(e){saveStatus('Browser storage is unavailable or full. Download a backup now.');notify('Your changes are in this tab. Download a backup to keep them.');}if($('undo'))$('undo').disabled=!history.length;refresh();}
function change(fn){const next=structuredClone(project);fn(next);commit(next);}
function download(name,blob){const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function jsonDownload(name,data){download(name,new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));}
function persistSelection(){project={...project,selections:remember(project.selections,selection,shell,face)};try{localStorage.setItem(KEY,JSON.stringify(project));}catch{saveStatus('Selection is remembered in this tab only. Download a backup.');}}
function choose(t,{toggle=false}={}){if(t){t=validateTarget(t);shell=t.shell;face=t.face;pickKind=t.kind;if(t.kind==='facet'){const result=selectFacetGroup(project.facetSelections,t,toggle);project={...project,facetSelections:result.groups};t=result.focused;}}else project={...project,facetSelections:{...project.facetSelections,[`${shell}/${face}`]:[]}};selection=t;cell=t&&t.kind!=='volume'?t.index:null;selectedId=null;persistSelection();refresh();}
function pick(t,event={}){choose(t,{toggle:t.kind==='facet'&&(multipleFacets||event.shiftKey||event.ctrlKey||event.metaKey)});}
function select(s,c,f=face,event={}){pick(target(s,f,['stack','volume'].includes(pickKind)?'facet':pickKind,c),event);}
function selectAllFacets(){multipleFacets=true;const cells=Array.from({length:288},(_,i)=>i+1);project={...project,facetSelections:{...project.facetSelections,[`${shell}/${face}`]:cells}};selection=target(shell,face,'facet',selection?.kind==='facet'?selection.index:1);pickKind='facet';selectedId=null;persistSelection();refresh();}
function switchOwner(s,f=face){shell=s;face=f;if(facetCells().length>1)multipleFacets=true;selection=remembered(project.selections,shell,face);if(selection)pickKind=selection.kind;cell=selection&&selection.kind!=='volume'?selection.index:null;selectedId=null;refresh();}
function selectOptions(node,items,value){node.replaceChildren();for(const [v,name]of items){const o=el('option',name);o.value=v;node.append(o);}if(value!==undefined)node.value=value;}
function refresh(){
  document.documentElement.style.setProperty('--shell',SHELLS[shell][1]);
  selection=remembered(project.selections,shell,face);if(selection)pickKind=selection.kind;cell=selection&&selection.kind!=='volume'?selection.index:null;
  if(pickedFacets().length>1)multipleFacets=true;
  const selectedLabel=selection?targetLabel(selection):`${SHELLS[shell][0]} ${face} · Nothing selected`;
  if($('selected-address'))$('selected-address').textContent=selectedLabel;
  if($('stage-address'))$('stage-address').textContent=selectedLabel+(pickedFacets().length>1?` · ${pickedFacets().length} facets selected`:'');
  if($('address-detail'))$('address-detail').textContent=selection?`${KIND_NAMES[selection.kind]} · ${cell?`Row ${Math.floor((cell-1)/24)+1} · Column ${(cell-1)%24+1}`:'Shared cubic volume'}`:'Select a facet, edge, vertex or volume point to attach information.';
  document.querySelectorAll('[data-shell]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.shell===shell)));
  document.querySelectorAll('[data-face]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.face===face)));
  if(view){view.selection=selection;view.selectedFacets=pickedFacets().map(t=>t.index);view.kind=pickKind==='stack'?'facet':pickKind;view.vectors=project.vectors;view.stacks=project.stacks;view.records=project.records;view.links=project.links;view.set(page==='story'?poseAt(project.story,time).pose:{...PRESETS[shape]},shell,cell,face);}
  if(page==='matrix'){renderGrid();renderRecords();spatialUI?.refresh();document.dispatchEvent(new CustomEvent('aura-selection-change',{detail:selection}));}
  if(page==='inventory')renderInventory();
  if(page==='story'){renderShots();updateTimeline();}
  if($('record-count'))$('record-count').textContent=`${project.records.length} records · ${project.links.length} connections`;
}
if($('aura-canvas')){
  try{view=new AuraView($('aura-canvas'),pick);}catch(e){$('stage-error').textContent='The 3D view needs WebGL. You can still use the numbered matrix, records and backups below.';}
  for(let s=6;s>=0;s--){const b=el('button');b.dataset.shell=s;b.style.setProperty('--colour',SHELLS[s][1]);b.title=SHELLS[s][0];b.setAttribute('aria-label',`Select ${SHELLS[s][0]} shell`);b.setAttribute('aria-pressed',String(s===shell));b.onclick=()=>{if(!recording)switchOwner(s);};$('shell-rail').append(b);}
  $('reset-view').onclick=()=>view?.reset();
  $('save-png').onclick=()=>{if(!view)return notify('PNG export needs the 3D view.');const c=document.createElement('canvas');c.width=1280;c.height=720;view.paintExport(c.getContext('2d'),1280,720,page==='story'?poseAt(project.story,time).caption:`${PRESETS[shape].name}. Twelve rows, twenty-four columns.`,page==='story'&&$('include-labels').checked);c.toBlob(b=>b&&download('aura-matrix-frame.png',b),'image/png');};
}
document.querySelectorAll('[data-face]').forEach(b=>b.onclick=()=>switchOwner(shell,b.dataset.face));
if(page==='matrix'){
  for(const [key,p]of Object.entries(PRESETS)){const b=el('button',p.name);b.dataset.shape=key;b.setAttribute('aria-pressed',String(key===shape));b.onclick=()=>{shape=key;document.querySelectorAll('[data-shape]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));refresh();view?.reset();};$('shapes').append(b);}
  for(let i=1;i<=288;i++){const b=el('button',String(i));b.dataset.cell=i;b.onclick=e=>select(shell,i,face,e);b.addEventListener('keydown',e=>{const key={ArrowUp:'north',ArrowRight:'east',ArrowDown:'south',ArrowLeft:'west'}[e.key];if(key){e.preventDefault();const next=neighbours(i)[key];select(shell,next);$('matrix-grid').children[next-1].focus();}});$('matrix-grid').append(b);}
  $('record-form').onsubmit=e=>{e.preventDefault();try{if(!selection)throw Error('Select an address first.');const title=$('record-title').value.trim();if(!title)return;const old=project.records.find(r=>r.id===selectedId),assetUrl=$('record-asset').value.trim(),instructions=$('record-instructions').value,rawData=$('record-data').value.trim();let data;if(rawData){try{data=JSON.parse(rawData);}catch{throw Error('Attached data must be valid JSON.');}}const record={id:old?.id||id(),title,note:$('record-note').value,shell,cell:cell||1,face,fields:old?.fields||{},...(selection.kind!=='facet'?{anchor:selection}:{}),...(assetUrl?{asset:{url:assetUrl}}:{}),...(instructions?{instructions}:{}),...(data!==undefined?{data}:{})};change(p=>{const i=p.records.findIndex(r=>r.id===record.id);if(i<0)p.records.push(record);else p.records[i]=record;});selectedId=record.id;renderRecords();notify('Saved at '+targetLabel(selection)+'.');}catch(error){notify(error.message);}};
  $('new-record').onclick=()=>{selectedId=null;renderRecords();$('record-title').focus();};
  $('delete-record').onclick=()=>{const rid=selectedId;selectedId=null;change(p=>{p.records=p.records.filter(r=>r.id!==rid);p.links=p.links.filter(l=>l.from!==rid&&l.to!==rid);});notify('Record removed. Undo will restore it.');};
  $('connection-form').onsubmit=e=>{e.preventDefault();const to=$('link-to').value,label=$('link-label').value.trim();if(!selectedId||!to||!label)return;change(p=>p.links.push({from:selectedId,to,label}));notify('Connection saved.');};
}
function renderGrid(){const occupied=new Set(project.records.filter(r=>r.shell===shell&&r.face===face&&recordTarget(r).kind===pickKind).map(r=>r.cell));for(const b of $('matrix-grid').children){const n=+b.dataset.cell;const selected=pickKind==='facet'&&pickedFacets().some(t=>t.index===n)||selection&&selection.kind===pickKind&&selection.kind!=='volume'&&selection.index===n;b.classList.toggle('occupied',occupied.has(n));b.setAttribute('aria-pressed',String(Boolean(selected)));b.setAttribute('aria-label',`${SHELLS[shell][0]} ${face} ${KIND_NAMES[pickKind]||'Facet'} ${n}${occupied.has(n)?', contains records':''}`);b.tabIndex=(selection?.index===n)||((!selection||selection.kind!==pickKind)&&n===1)?0:-1;b.replaceChildren(document.createTextNode(String(n)));const stack=project.stacks.find(s=>s.shell===shell&&s.face===face&&s.cell===n);if(stack){const badge=el('sup','+'+stack.count,'stack-badge');b.append(badge);}}}
function renderRecords(){
  const list=$('cell-records');list.replaceChildren();const records=recordsAt(project.records,selection);
  if(!records.length)list.append(el('p',selection?'No records at this address. Add data, instructions or an asset below.':'This torus has no active selection. Choose an address to begin.','empty'));
  $('record-form').querySelectorAll('input,textarea,button').forEach(n=>n.disabled=!selection);
  if(records.length){const choices=el('select');choices.setAttribute('aria-label','Records at this address');selectOptions(choices,[['',`New record (${records.length} saved here)`],...records.map(r=>[r.id,r.title])],selectedId||'');choices.onchange=()=>{selectedId=choices.value||null;renderRecords();};list.append(choices);const active=records.find(r=>r.id===selectedId);if(active?.asset){const a=el('a','Open attached asset','asset-link');a.href=active.asset.url;a.target='_blank';a.rel='noopener noreferrer';list.append(a);}}
  const r=project.records.find(r=>r.id===selectedId);$('form-state').textContent=r?'Editing selected record':'New record at this address';$('record-title').value=r?.title||'';$('record-note').value=r?.note||'';$('record-asset').value=r?.asset?.url||'';$('record-instructions').value=r?.instructions||'';$('record-data').value=r?.data!==undefined?JSON.stringify(r.data,null,2):'';$('delete-record').hidden=!r;$('new-record').hidden=!r;
  $('connections-editor').hidden=!r;$('record-fields').replaceChildren();
  if(r){for(const [k,v] of Object.entries(r.fields||{})){$('record-fields').append(el('dt',k),el('dd',v));}}
  selectOptions($('link-to'),[['','Choose another record'],...project.records.filter(x=>x.id!==selectedId).map(x=>[x.id,`${x.title} · ${targetLabel(recordTarget(x))}`])]);$('link-label').value='';$('connections').replaceChildren();
  for(const l of project.links.filter(x=>x.from===selectedId||x.to===selectedId)){const a=project.records.find(r=>r.id===l.from),b=project.records.find(r=>r.id===l.to),n=el('div',`${a.title} → ${l.label} → ${b.title}`,'connection'),remove=el('button','Remove');remove.onclick=()=>change(p=>p.links.splice(project.links.indexOf(l),1));n.append(remove);$('connections').append(n);}
}
function renderInventory(){const q=$('search').value.toLowerCase(),rows=project.records.filter(r=>`${r.title} ${r.note} ${targetLabel(recordTarget(r))} ${JSON.stringify(r.fields)}`.toLowerCase().includes(q));$('inventory-rows').replaceChildren();for(const r of rows){const tr=el('tr');tr.append(el('td',r.title),el('td',targetLabel(recordTarget(r))),el('td',r.note,'note-cell'));const td=el('td'),b=el('button','Open cell');b.onclick=()=>{const t=recordTarget(r);location.href='matrix.html?'+new URLSearchParams({...t,index:String(t.index)}).toString();};td.append(b);tr.append(td);$('inventory-rows').append(tr);}$('inventory-empty').hidden=rows.length>0;$('inventory-count').textContent=`${rows.length} of ${project.records.length} records`;}
if($('search'))$('search').oninput=renderInventory;
if($('undo'))$('undo').onclick=()=>{if(!history.length)return;spatialUI?.stop();const previous=history.pop();project=previous;selectedId=null;try{localStorage.setItem(KEY,JSON.stringify(project));saveStatus('Saved on this browser');}catch{saveStatus('Undo is in this tab. Download a backup.');}$('undo').disabled=!history.length;refresh();notify('Last change undone.');};
document.querySelectorAll('[data-backup]').forEach(b=>b.onclick=()=>jsonDownload('aura-matrix-backup.json',project));
document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>$('backup-file').click());
$('backup-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{const next=validateProject(JSON.parse(await file.text()));$('restore-summary').textContent=`This backup contains ${next.records.length} records, ${next.links.length} connections and ${next.story.length} explainer shots. Restore will replace this browser's project. You can download your current backup first.`;$('restore-confirm').onclick=()=>{stopPlayback();spatialUI?.stop();selectedId=null;time=0;shotIndex=0;commit(next);$('restore-dialog').close();notify('Backup restored.');};$('restore-dialog').showModal();}catch(error){notify(error.message);}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{const records=exampleRecords(id);change(p=>{p.records.push(...records);p.links.push({from:records[0].id,to:records[1].id,label:'raises a question'},{from:records[1].id,to:records[2].id,label:'explored through'},{from:records[2].id,to:records[3].id,label:'suggests an action'});});if(page==='matrix')choose(target(0,'I','facet',97));notify('Four clearly labelled example records added. Your existing records are kept.');});
document.querySelectorAll('[data-csv]').forEach(b=>b.onclick=()=>$('csv-file').click());
$('csv-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{pendingCSV=parseCSV(await file.text());selectOptions($('csv-title'),pendingCSV.headers.map(h=>[h,h]));selectOptions($('csv-note'),[['','No note column'],...pendingCSV.headers.map(h=>[h,h])]);selectOptions($('csv-cell'),[['','Place consecutive rows from the starting cell'],...pendingCSV.headers.map(h=>[h,h])]);selectOptions($('csv-shell'),SHELLS.map((s,i)=>[i,s[0]]),shell);$('csv-start').value=cell||1;$('csv-error').textContent='';$('csv-face').value=face;$('csv-summary').textContent=`${file.name}: ${pendingCSV.rows.length} rows. All original columns are kept with each record.`;$('csv-preview').textContent=pendingCSV.headers.join(' | ')+'\n'+pendingCSV.rows.slice(0,3).map(r=>r.join(' | ')).join('\n');$('csv-dialog').showModal();}catch(error){notify(error.message);}};
$('csv-form').onsubmit=e=>{e.preventDefault();try{const mapping={title:$('csv-title').value,note:$('csv-note').value,cell:$('csv-cell').value,shell:+$('csv-shell').value,start:+$('csv-start').value,face:$('csv-face').value};const records=recordsFromCSV(pendingCSV,mapping,id);change(p=>p.records.push(...records));$('csv-dialog').close();notify(`${records.length} records placed. Download a backup to keep a separate copy.`);}catch(error){$('csv-error').textContent=error.message;}};
function stopPlayback(){playing=false;playingLast=0;if($('play'))$('play').textContent='Play explainer';if(view)view.locked=Boolean(recording);}
function renderShots(){
  shotIndex=Math.min(shotIndex,project.story.length-1);$('shot-list').replaceChildren();project.story.forEach((s,i)=>{const li=el('li'),b=el('button');b.append(el('span',String(i+1),'shot-number'));const label=el('span',PRESETS[s.preset].name);label.append(el('small',`${s.duration} seconds`));b.append(label);b.setAttribute('aria-pressed',String(i===shotIndex));b.onclick=()=>{stopPlayback();shotIndex=i;time=project.story.slice(0,i).reduce((n,s)=>n+s.duration,0)+Math.min(3,s.duration*.65);refresh();};li.append(b);$('shot-list').append(li);});
  const shot=project.story[shotIndex];selectOptions($('shot-preset'),Object.entries(PRESETS).map(([k,v])=>[k,v.name]),shot.preset);selectOptions($('shot-camera'),[['front','Front'],['quarter','Three quarter'],['top','From above']],shot.camera);$('shot-duration').value=shot.duration;$('shot-caption').value=shot.caption;$('delete-shot').disabled=project.story.length===1;$('shot-editor-title').textContent=`Edit shot ${shotIndex+1}`;
}
function updateTimeline(){const at=poseAt(project.story,time);time=at.time;$('scrub').max=at.total;$('scrub').value=time;$('time-label').textContent=`${time.toFixed(1)} / ${at.total.toFixed(1)} sec`;$('caption').textContent=at.caption;if(view)view.set(at.pose,shell,cell,face);}
if(page==='story'){
  $('play').onclick=()=>{if(playing){stopPlayback();return;}if(time>=poseAt(project.story,time).total)time=0;playing=true;playingLast=0;if(view)view.locked=true;$('play').textContent='Pause';};
  $('restart').onclick=()=>{stopPlayback();time=0;updateTimeline();};$('scrub').oninput=e=>{stopPlayback();time=+e.target.value;updateTimeline();};
  $('shot-form').onsubmit=e=>{e.preventDefault();stopPlayback();change(p=>p.story[shotIndex]={preset:$('shot-preset').value,camera:$('shot-camera').value,duration:+$('shot-duration').value,caption:$('shot-caption').value});notify('Explainer shot saved.');};
  $('add-shot').onclick=()=>{stopPlayback();const shot=structuredClone(project.story[shotIndex]);shotIndex=project.story.length;change(p=>p.story.push(shot));};
  $('delete-shot').onclick=()=>{if(project.story.length<2)return;stopPlayback();const old=shotIndex;shotIndex=Math.max(0,shotIndex-1);time=0;change(p=>p.story.splice(old,1));};
  $('move-shot-up').onclick=()=>{if(shotIndex<1)return;stopPlayback();const old=shotIndex;shotIndex--;time=0;change(p=>[p.story[old-1],p.story[old]]=[p.story[old],p.story[old-1]]);};
  $('story-json').onclick=()=>jsonDownload('aura-explainer.json',{format:'aura-explainer/1',lattice:LATTICE,rows:ROWS,columns:COLS,shell,cell:cell||1,face,story:project.story});
  $('record-video').onclick=exportVideo;
  if(!globalThis.MediaRecorder||!HTMLCanvasElement.prototype.captureStream){$('record-video').disabled=true;$('video-hint').textContent='Video recording is unavailable in this browser. Use the PNG and explainer file exports.';}
  function tick(now){if(playing&&!recording){if(playingLast)time+=(now-playingLast)/1000;playingLast=now;updateTimeline();if(time>=poseAt(project.story,time).total)stopPlayback();}requestAnimationFrame(tick);}requestAnimationFrame(tick);
}
async function exportVideo(){
  if(recording){recording.cancelled=true;recording.recorder.stop();return;}
  if(!view)return notify('Video export needs the 3D view.');
  const type=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!type)return notify('This browser cannot record WebM. Use Chrome or Edge, or export the explainer file.');
  stopPlayback();const previousTime=time,previousTheta=view.theta,previousPhi=view.phi;
  const output=document.createElement('canvas');output.width=1280;output.height=720;const ctx=output.getContext('2d');
  const stream=output.captureStream(30);let recorder;try{recorder=new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:6000000});}catch(e){stream.getTracks().forEach(t=>t.stop());return notify('The browser could not start recording. Try PNG or the explainer file.');}
  const chunks=[],session={recorder,cancelled:false,frame:null};recording=session;view.locked=true;
  document.querySelectorAll('main button,main input,main select,main textarea').forEach(n=>{if(n.id!=='record-video'){n.dataset.wasDisabled=String(n.disabled);n.disabled=true;}});
  $('record-video').textContent='Cancel recording';$('record-video').classList.add('recording');$('video-hint').textContent='Recording the complete sequence at 1280 × 720. Keep this tab visible. No sound is recorded.';
  const onHide=()=>{if(document.hidden&&recording){session.cancelled=true;recorder.stop();notify('Recording cancelled because the tab was hidden. Keep it visible for a complete video.');}};document.addEventListener('visibilitychange',onHide);
  recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};
  recorder.onerror=()=>{session.cancelled=true;notify('The browser could not finish the recording.');if(recorder.state!=='inactive')recorder.stop();};
  recorder.onstop=()=>{cancelAnimationFrame(session.frame);document.removeEventListener('visibilitychange',onHide);stream.getTracks().forEach(t=>t.stop());recording=null;view.locked=false;time=previousTime;updateTimeline();view.theta=previousTheta;view.phi=previousPhi;view.render();document.querySelectorAll('[data-was-disabled]').forEach(n=>{n.disabled=n.dataset.wasDisabled==='true';delete n.dataset.wasDisabled;});$('record-video').textContent='Record video';$('record-video').classList.remove('recording');$('video-hint').textContent='1280 × 720 WebM video. Captions included. Silent, ready for a voice-over.';if(!session.cancelled&&chunks.length){download('aura-explainer.webm',new Blob(chunks,{type}));notify('Explainer video downloaded.');}};
  time=0;updateTimeline();view.paintExport(ctx,1280,720,poseAt(project.story,0).caption,$('include-labels').checked);recorder.start(1000);const start=performance.now(),total=poseAt(project.story,0).total;
  const frame=now=>{if(session.cancelled)return;try{time=Math.min(total,(now-start)/1000);updateTimeline();view.paintExport(ctx,1280,720,poseAt(project.story,time).caption,$('include-labels').checked);if(time>=total){recorder.stop();return;}session.frame=requestAnimationFrame(frame);}catch(e){session.cancelled=true;recorder.stop();notify('Recording stopped. Your project is unchanged.');}};session.frame=requestAnimationFrame(frame);
}
if(page==='matrix')spatialUI=mountSpatial({project:()=>project,selection:()=>selection,owner:()=>({shell,face}),select:choose,pick,facets:pickedFacets,multiple:()=>multipleFacets,selectAllFacets,setMultiple:value=>{multipleFacets=value;if(selection?.kind==='facet'&&(!value||!facetCells().length))choose(selection);else refresh();},change,notify,export:jsonDownload,setKind:(kind,redraw=true)=>{pickKind=kind;if(view){view.kind=kind==='stack'?'facet':kind;if(redraw){view.update();renderGrid();}}},layers:options=>{if(view){if(options.explode!==undefined){view.explodeStacks=options.explode;view.pose={...view.pose,explodeStacks:options.explode};}if(options.rays!==undefined)view.rayMode=options.rays;if(options.volume!==undefined)view.showVolume=options.volume;view.update();}},sequence:program=>{if(view){view.sequence=program;view.drawSpatial();view.render();}}});
const params=new URLSearchParams(location.search);if(/^[0-6]$/.test(params.get('shell')||'')&&['I','O'].includes(params.get('face'))){shell=+params.get('shell');face=params.get('face');}if(params.has('cell')||params.has('index'))try{const kind=params.get('kind')||'facet',value=params.get('index')||params.get('cell'),t=target(+params.get('shell'),params.get('face'),kind,kind==='volume'?value:+value,params.has('layer')?+params.get('layer'):undefined);const next={...project,selections:remember(project.selections,t)};project=validateProject(next);shell=t.shell;face=t.face;pickKind=t.kind;}catch{shell=0;cell=null;face='O';}
refresh();
if(page==='matrix'){mountWorkspace();if(new URLSearchParams(location.search).has('embedded'))document.body.classList.add('embedded-studio');const back=document.querySelector('.brand');back.title='Return to the Aura app';const from=new URLSearchParams(location.search).get('from');if(from&&/^[A-F0-9-]{36}$/.test(from))back.href='index.html?page='+from;}
// Local-only interface: no analytics, upload endpoint, external model or automatic sharing.
window.addEventListener('storage',e=>{if(e.key===KEY)notify('This project changed in another tab. Download this tab’s backup before reloading if you have unsaved edits.');});
