import {parseCSV,validateProject} from './core.js?v=0.3.9';
export const EARTH='A54DE2EE-A009-467A-BE13-BA8C3BDF1018',EARTH_WIDE='665135E8-D026-47B2-8F17-01F31A8910C1';
export const affinityName=name=>/(?<!\w)(aura|chakra|aurora|gajra|yoga|tai[ -]?chi|taichi)(?!\w)/iu.test(name.normalize('NFKD').replace(/\p{M}/gu,''));
export function earthRows(layer,rows){return rows.map((r,i)=>({id:layer.id+':'+i,layer:layer.id,name:r[0],lat:r[1],lng:r[2],detail:r[3]||'',category:r[4]||'',url:/^https?:\/\//i.test(r[5]||'')?r[5]:'',search:r[6]||'',colour:layer.colour}));}
export function filterEarth(rows,{layers,query='',filterAffinity=true}){const words=query.toLowerCase().trim().split(/\s+/).filter(Boolean);return rows.filter(r=>layers.has(r.layer)&&(!filterAffinity||r.layer!=='aura-affinity'||affinityName(r.name))&&words.every(w=>(r.name+' '+r.detail+' '+r.category+' '+r.search).toLowerCase().includes(w)));}
const point=r=>{const lat=Number(r.lat),lng=Number(r.lng);if(r.lat==null||r.lng==null||String(r.lat).trim()===''||String(r.lng).trim()==='' ||!Number.isFinite(lat)||!Number.isFinite(lng)||lat< -90||lat>90||lng< -180||lng>180)throw Error('Each point needs valid latitude and longitude.');if(!String(r.name||'').trim())throw Error('Give each point a name.');return {name:String(r.name).trim(),lat,lng,detail:String(r.detail||'')};};
export function importEarthPoints(text,filename){
 if(/\.csv$/i.test(filename)){const {headers:header,rows}=parseCSV(text),h=header?.map(s=>s.trim().toLowerCase());if(!h)throw Error('The CSV is empty.');const column=(names)=>names.map(n=>h.indexOf(n)).find(i=>i>=0),name=column(['name','title']),lat=column(['latitude','lat']),lng=column(['longitude','lng','lon']),detail=column(['notes','description','detail']);if(name===undefined||lat===undefined||lng===undefined)throw Error('CSV needs name, latitude and longitude columns.');return rows.filter(r=>r.some(v=>v.trim())).map(r=>point({name:r[name],lat:r[lat],lng:r[lng],detail:r[detail]}));}
 const data=JSON.parse(text),features=data.type==='FeatureCollection'?data.features:data.type==='Feature'?[data]:[];if(!Array.isArray(features)||!features.length)throw Error('Import a GeoJSON FeatureCollection of named points.');
 return features.flatMap(f=>{if(!['Point','MultiPoint'].includes(f.geometry?.type))throw Error('This importer accepts Point and MultiPoint geometry. Lines and polygons need a separate layer.');return (f.geometry.type==='Point'?[f.geometry.coordinates]:f.geometry.coordinates).map(c=>point({name:f.properties?.name||f.properties?.title,lat:c[1],lng:c[0],detail:f.properties?.description||f.properties?.notes}));});
}
export function saveEarthPoints(project,points,source='Dropped pin'){
 const checked=points.map(point),p=structuredClone(project);let t=p.tables.find(t=>t.id==='aura-earth-pins');if(!t){t={id:'aura-earth-pins',name:'My Earth places',category:'place',recommendation:'places',columns:['Title','Latitude','Longitude','Notes','Source'],rows:[],chakraTags:[0,6]};p.tables.push(t);}
 for(const c of ['Title','Latitude','Longitude','Notes','Source'])if(!t.columns.includes(c)){t.columns.push(c);t.rows.forEach(r=>r.values.push(''));}
 for(const r of checked){const values={Title:r.name,Latitude:String(r.lat),Longitude:String(r.lng),Notes:r.detail,Source:source};t.rows.push({id:crypto.randomUUID(),values:t.columns.map(c=>values[c]||'')});}return validateProject(p);
}
export function personalEarthRows(p){return p.tables.filter(t=>t.recommendation==='places'&&t.columns.includes('Latitude')&&t.columns.includes('Longitude')).flatMap(t=>t.rows.flatMap(r=>{const v=Object.fromEntries(t.columns.map((c,i)=>[c,r.values[i]]));try{return [{...point({name:v.Title,lat:v.Latitude,lng:v.Longitude,detail:v.Notes}),id:t.id+':'+r.id,layer:'personal',colour:'#e34b34',tableId:t.id,rowId:r.id}];}catch{return [];}}));}
// Screen-space grouping draws every matching point, using count markers when close.
export function clusterEarth(rows,project,size=30){const groups=new Map();for(const r of rows){const p=project(r);if(!p)continue;const key=Math.floor(p.x/size)+':'+Math.floor(p.y/size);let g=groups.get(key);if(!g){g={first:r,count:0,members:[]};groups.set(key,g);}g.count++;g.members.push(r);}return [...groups.values()];}

// Pick in the same original-frame coordinates used to draw and drag the map.
export function pickEarthMarker(markers,point){let hit=null,distance=Infinity;for(const marker of markers){const d=Math.hypot(marker.point.x-point.x,marker.point.y-point.y);if(d<=Math.max(12,marker.radius)&&d<=distance){hit=marker;distance=d;}}return hit;}
