import {mountTimeContext} from './time-context.js?v=0.3.9';
import {TRAVEL,TIMELINES,CELESTIAL,readTravelProject,writeTravelProject,travelEntries,travelProgress,travelGoal,saveTrip,saveTravelGoal,normaliseDestination,travelTimeline} from './travel-data.js?v=0.3.9';
const make=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;};
const button=(text,fn)=>{const n=make('button','',text);n.type='button';n.onclick=fn;return n;};
const field=(form,label,type,value='')=>{const n=make('input');n.type=type;n.value=value;n.setAttribute('aria-label',label);const l=make('label');l.append(make('span','',label),n);form.append(l);return n;};
let seed;
export function travelSeed(){return seed||(seed=fetch('assets/travel-destinations.json?v=0.3.9').then(r=>{if(!r.ok)throw Error('The destination list could not load. You can still type a place.');return r.json();}).catch(e=>{seed=null;throw e;}));}
export function tripForm(container,{entry=null,onSave=()=>{},initialStatus='Want to go',brief=false}={}){
 const form=make('form','travel-form'),message=make('p','travel-message');message.setAttribute('role','status');const tabs=make('nav','travel-form-tabs');let pane='place';const groups={};
 const values=entry||{},place=make('div');groups.place=place;
 const destination=field(place,initialStatus==='Visited'?'Where have you travelled?':'Where do you want to travel?','text',values.Destination||values.Title||'');destination.required=true;destination.maxLength=200;
 const list=make('datalist');list.id='travel-choices-'+crypto.randomUUID();destination.setAttribute('list',list.id);place.append(list);travelSeed().then(data=>{if(!list.isConnected)return;for(const r of data.destinations){const o=make('option');o.value=r.name;list.append(o);}}).catch(e=>message.textContent=e.message);
 const status=make('select');status.setAttribute('aria-label','Travel status');for(const value of ['Visited','Want to go','Planned']){const o=make('option','',value);o.value=value;status.append(o);}status.value=values.Status||initialStatus;const sl=make('label');sl.append(make('span','','Travel status'),status);place.append(sl);
 const timing=make('div');groups.timing=timing;const start=field(timing,'Departure or visit date','date',values.Date||''),end=field(timing,'Return date (optional)','date',values['Return date']||'');
 const hemisphere=make('select');hemisphere.setAttribute('aria-label','Seasonal region');for(const [id,text]of [['','Choose seasonal region'],['north','Northern hemisphere'],['south','Southern hemisphere'],['local','Local wet / dry or mixed seasons']]){const o=make('option','',text);o.value=id;hemisphere.append(o);}hemisphere.value=values.Hemisphere||'';const hl=make('label');hl.append(make('span','','Seasonal region'),hemisphere);timing.append(hl);
 const notes=make('div');groups.notes=notes;const season=field(notes,'Preferred season or local conditions','text',values['Preferred season']||''),astrology=field(notes,'Astrology notes or preferred timing','text',values['Astrology notes']||''),purpose=field(notes,'What would you like to do there?','text',values.Purpose||'');
 if(!brief){for(const [id,label]of [['place','Place'],['timing','Dates'],['notes','Intentions']]){const b=button(label,()=>{pane=id;render();});b.dataset.pane=id;tabs.append(b);}form.append(tabs);}
 form.append(place,timing,notes);function render(){Object.entries(groups).forEach(([id,g])=>g.hidden=id!==pane);for(const b of tabs.children)b.setAttribute('aria-pressed',String(b.dataset.pane===pane));}render();
 const save=make('button','travel-primary','Save place');save.type='submit';form.append(save,message);container.append(form);
 form.onsubmit=e=>{e.preventDefault();try{if(!form.reportValidity())return;const fields={Destination:destination.value,Status:status.value,Date:start.value,'Return date':end.value,Hemisphere:hemisphere.value,'Preferred season':season.value,'Astrology notes':astrology.value,Purpose:purpose.value};writeTravelProject(p=>saveTrip(p,fields,entry?.id?entry:null));onSave(fields);message.textContent='Saved in your travel list and Aura tables.';}catch(e){message.textContent=e.message;}};
 return form;
}
export function goalForm(container,onSave=()=>{}){
 const goal=travelGoal(readTravelProject()),form=make('form','travel-form'),target=field(form,'Countries and territories','number',goal.target),years=field(form,'Over how many years?','number',goal.years),start=field(form,'Start date (optional)','date',goal.start);target.min=1;target.step=1;target.required=true;years.min=.01;years.step='any';years.required=true;const save=make('button','travel-primary','Save travel goal'),message=make('p','travel-message');save.type='submit';form.append(save,message);container.append(form);form.onsubmit=e=>{e.preventDefault();try{writeTravelProject(p=>saveTravelGoal(p,{target:+target.value,years:+years.value,start:start.value}));onSave();message.textContent='Travel goal saved.';}catch(e){message.textContent=e.message;}};
}
export function mountTravel({page,screen,go}){
 let disposed=false,entries=[],destinations=[],mode='all',query='',offset=0;
 const source=page.controls.find(c=>c.controlTypeID==='ScrollView');screen.querySelector(`[data-source-control="${source.controlID}"]`).hidden=true;
 for(const c of page.controls)if(c.controlTypeID==='Icon'&&+c.x===168){const a=screen.querySelector(`[data-source-control="${c.controlID}"] a`);if(a){a.href='?page='+TIMELINES;a.setAttribute('aria-label','Travel timelines');a.title='Travel timelines';a.onclick=e=>{e.preventDefault();go(TIMELINES);};}}
 const panel=make('section','travel-panel'),summary=button('',()=>openGoal()),add=button('+ Add',()=>edit(null)),top=make('div','travel-top');top.append(summary,add);panel.append(top);
 const tabs=make('nav','travel-tabs'),search=make('input');search.type='search';search.placeholder='Find a country or territory';search.setAttribute('aria-label',search.placeholder);panel.append(tabs,search);
 const list=make('div','travel-list'),pager=make('div','travel-pager'),prev=button('‹',()=>{offset-=3;draw();}),next=button('›',()=>{offset+=3;draw();}),count=make('span');prev.setAttribute('aria-label','Previous destinations');next.setAttribute('aria-label','More destinations');pager.append(prev,count,next);panel.append(list,pager);
 const footer=make('div','travel-links');footer.append(button('Planning tools',()=>openTools()),button('Travel timeline',()=>go(TIMELINES)));panel.append(footer);screen.append(panel);
 const dialog=make('dialog','travel-dialog'),head=make('header'),heading=make('h2'),close=button('Done',()=>dialog.close()),body=make('div','travel-dialog-body');head.append(heading,close);dialog.append(head,body);document.body.append(dialog);
 function openGoal(){heading.textContent='Your travel goal';body.replaceChildren();goalForm(body,()=>{dialog.close();draw();});dialog.showModal();}
 function edit(item){heading.textContent=item?'Edit travel plans':'Add a place';body.replaceChildren();tripForm(body,{entry:item,onSave:()=>{dialog.close();draw();}});if(item?.id)body.append(button('Remove this trip',()=>{writeTravelProject(p=>{const t=p.tables.find(t=>t.id===item.tableId);t.rows=t.rows.filter(r=>r.id!==item.id);return p;});dialog.close();draw();}));dialog.showModal();}
 function openTools(){heading.textContent='Travel planning tools';body.replaceChildren(make('p','','Use your existing tools to work through routes, entry, activities and preparation.'));for(const [label,url]of [['Travel Oracle builders','strange-but-true-travel-oracle/builders.html'],['World travel destinations','Australian-world-travel/'],['Long-range route planner','Australian-world-travel/strategy.html'],['Visa and logistics tracker','Australian-world-travel/logistics.html'],['Visa and activity atlas','Australian-visa-activity-atlas/'],['Compare activity routes','Australian-visa-activity-atlas/compare.html'],['Preparation checklist','Australian-visa-activity-atlas/prepare.html']]){const a=make('a','travel-tool',label);a.href='https://auraofintelligence.github.io/'+url;a.target='_blank';a.rel='noopener';body.append(a);}body.append(button('Celestial timing',()=>{dialog.close();go(CELESTIAL);}));dialog.showModal();}
 function draw(){const project=readTravelProject(),progress=travelProgress(project);entries=travelEntries(project);summary.textContent=`${progress.visited} / ${progress.target} visited · ${progress.years} years`;summary.setAttribute('aria-label','Edit travel goal');tabs.replaceChildren();for(const [id,label]of [['all','All'],['Visited','Been'],['Want to go','Want'],['Planned','Planned']]){const b=button(label,()=>{mode=id;offset=0;draw();});b.setAttribute('aria-pressed',String(id===mode));tabs.append(b);}
  let items=mode==='all'?[...destinations.map(d=>({Destination:d.name})),...entries.filter(r=>!destinations.some(d=>normaliseDestination(d.name)===normaliseDestination(r.Destination||r.Title)))]:entries.filter(r=>r.Status===mode);
  items=items.filter(r=>normaliseDestination(r.Destination||r.Title||'').includes(normaliseDestination(query)));offset=Math.max(0,Math.min(offset,Math.max(0,Math.floor((items.length-1)/3)*3)));list.replaceChildren();
  for(const item of items.slice(offset,offset+3)){const matching=item.id?item:entries.find(r=>normaliseDestination(r.Destination||r.Title)===normaliseDestination(item.Destination));const b=button('',()=>edit(matching||{...item,Status:'Want to go'}));b.append(make('strong','',item.Destination||item.Title),make('small','',matching?.Status||'Add to your travel list'));list.append(b);}
  if(!items.length)list.append(make('p','','Add a place you have visited or want to visit.'));count.textContent=items.length?`${offset+1}-${Math.min(offset+3,items.length)} / ${items.length}`:'Your list starts here';prev.disabled=offset===0;next.disabled=offset+3>=items.length;
 }
 search.oninput=()=>{query=search.value;offset=0;draw();};travelSeed().then(data=>{if(!disposed){destinations=data.destinations;draw();}}).catch(()=>{});draw();dialog.addEventListener('close',draw);return {resize(){},dispose(){disposed=true;dialog.remove();}};
}
export function mountTravelTimeline({screen,go}){
 const context=mountTimeContext(screen);
 const launch=button('Travel timeline',()=>{draw();dialog.showModal();});launch.className='travel-timeline-launch';screen.append(launch);
 const dialog=make('dialog','travel-dialog'),header=make('header');header.append(make('h2','','Travel timeline'),button('Done',()=>dialog.close()));const body=make('div','travel-dialog-body');dialog.append(header,body);document.body.append(dialog);let offset=0;
 function draw(){const entries=travelTimeline(readTravelProject());body.replaceChildren();for(const r of entries.slice(offset,offset+5)){const b=button('',()=>{dialog.close();go(CELESTIAL,{trip:r.id,table:r.tableId});});b.className='travel-timeline-item';b.append(make('strong','',r.Destination||r.Title),make('span','',`${r.Date}${r['Return date']?' to '+r['Return date']:''}`),make('small','',`${r.Status||'Trip'} · Open celestial timing`));body.append(b);}if(!entries.length)body.append(make('p','','Add a departure or visit date in Travel Plans. Your trips will appear here in date order.'));const pager=make('div','travel-pager'),prev=button('‹',()=>{offset-=5;draw();}),next=button('›',()=>{offset+=5;draw();});prev.disabled=offset===0;next.disabled=offset+5>=entries.length;pager.append(prev,make('span','',`${entries.length} dated trips`),next);body.append(pager,button('Travel plans',()=>{dialog.close();go(TRAVEL);}),button('Celestial clock',()=>{dialog.close();go(CELESTIAL);}));}
 return {resize(){},dispose(){context.dispose();dialog.remove();}};
}
